### ISSUE TITLE
install via f-droid triggers "Blocked by Play Protect"

### ISSUE THREAD

**Issue by tharvik** [c4dt/dp3t-app-android-ch#1] opened 2021-05-03 13:16 UTC
On a ~vanilla (FairPhone 3) Android, installing it via f-droid shows the following

![Screenshot_20210503-141712](https://user-images.githubusercontent.com/5735566/116880132-eae97a00-ac21-11eb-803c-a827a7a77f12.png)

It can anyway be installed but it's the only application I found doing that.

AFAIR Play Protect is installed alongside Play Store, it validates apps (signature, virus scan, ...).

**Comment by cgrigis** [comment] 2021-05-03 18:41
Reproduced on a Samsung A40.
What is strange is that after installing anyway, running a Play Protect scan results in "No harmful apps found". :man_shrugging:

**Comment by cgrigis** [comment] 2021-07-16 09:06
Possibly happens only on stock (proprietary) Android systems.
It looks like the message does not show up on later installs.
Closing it for now, as I am not clear on how to avoid it, and it does not prevent installation anyway.

**Closed as completed by cgrigis** 2021-07-16 09:06 UTC
Labels: enhancement
